version: 1.0.{build}
os: Windows Server 2012 R2
environment:
  nodejs_version: v0.12.0
install:
- npm install npm bower grunt-cli -g
- set PATH=%APPDATA%\npm;%PATH%
- npm install
- bower install
build_script:
- grunt build
test_script:
- grunt test